apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-backend
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-tomcat
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
