kind: Service
apiVersion: v1
metadata:
  name: { .Release.Name}-{ .Chart.Name}-service
  labels:
    app: { .Release.Name}-{ .Chart.Name}
spec:
  selector:
    app: { .Release.Name}-{ .Chart.Name}
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node

