apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-backend-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-backend
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 8080
      #nodePort: 32227
